language: cpp
os: linux
sudo: required
dist: bionic
addons:
  apt:
    update: true
    packages:
      - build-essential
      - pkg-config
      - faust
      - libjack-dev
script:
  - make
  - make -C examples
